##
# 3 tipos: docker-registry, generic, tls
# docker-registry -> DockerHub, etc...
# generic -> Cria de um arquivo local, diretorio ou valor literal
# tls -> Certificado tls

#kubectl create secret generic credentials --from-literal=username=admin

# A informação fica em base64
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kubernetes.io/basic-auth
data:
  username: bHVpeg==
  password: bHVpeg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
        - containerPort: 80
        env: 
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: credentials
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password
        volumeMounts:
        - name: credentials
          mountPath: "/tmp"
          readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: credentials