## Autoscaling
# default é CPU
# VerticalScaling = hardware
# HorizontalScaling = pods

# Exemplo: 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: myapp
    kind: Deployment
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15
  behavior:
    scaleDown:
      policies:
        - type: Percent
          value: 5
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tibursio/helloworld-nginx
        resources:
          requests:
            memory: "5Mi"
            cpu: "0.1"
          limits:
            memory: "10Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

## Stabilization window
# Muito mais usada para o scale down, do que o up.
# Padrão 300 segundos = 5 minutos
# Ajuda a não causar desrupção da aplicação
# Quando estabiliza por 5 minutos ele começa a diminuir o número de replicas
# Pode ser alterado na config do hpa